#!/usr/bin/env python3
"""
Converts AIM News Desk content-handoff records (handoff/<date>/<cluster_id>.json,
written by POST /stories/{id}/handoff) into the exact input shape the First
Signal News FB pipeline's batch_from_scrape.py expects: a JSON list of
{"text", "url", "image_url", ...} dicts (see --input memory/scrape-results.json
in that repo). batch_from_scrape.py takes posts in INPUT ORDER -- it does not
re-rank them itself -- so this script sorts by News Desk's own viral score
before writing, the same role rank_competitors.py plays for scraped posts.

This is the missing link the original Phase 1 spec called for: News Desk does
discovery + multi-source verification + ranking; this script hands its picks
to the pipeline that turns them into branded share-cards. It generates NO
captions or images itself, and never touches that pipeline's real
memory/scrape-results.json -- see the --out default below.

Usage:
    python scripts/adapter_to_first_signal.py --date 2026-07-21 --out "../../FIRST SIGNAL/AUTOMATION SOFTWARE/first_signal_news-pipeline-20260602/memory/from_newsdesk.json"
    python scripts/adapter_to_first_signal.py --cluster-id 1336 --out <path>
    python scripts/adapter_to_first_signal.py --out <path>   # all handoff records, any date

Design decision on image_url: batch_from_scrape.py only checks whether
image_url is PRESENT -- it never fetches or reuses its content. The actual
photo is always AI-generated by gpt-image-2 from a text description (a
detected public figure, or a generic on-topic scene); no source image is
ever passed through (per that pipeline's own IP-safety rule against reusing
a competitor's image as --image_input). Since that pipeline's product is
overwhelmingly image share-cards (12 images : 5 TOBI per default batch) and
an editor clicking "Send to Pipeline" has already judged the story worth
pushing, every handed-off story defaults to an image candidate here:
image_url is set to the real primary-source URL (not fabricated -- it's a
genuine link the editor can open), which doubles as the "url"/"post_url"
field batch_from_scrape.py uses for source attribution.
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
HANDOFF_DIR = REPO_ROOT / "handoff"

# Same pattern as app/entities.py's strip_source_suffix -- kept as an
# independent copy on purpose. This script is meant to run standalone
# against whatever pipeline consumes it, without importing across two
# separately-deployed repos.
_SOURCE_SUFFIX_RE = re.compile(r"\s+-\s+[^-]{2,40}$")


def clean_headline(headline: str) -> str:
    """Strip Google News' trailing ' - Outlet Name' so the destination
    pipeline's rendered headline doesn't end with an unrelated outlet name."""
    m = _SOURCE_SUFFIX_RE.search(headline)
    if m and len(headline) - len(m.group(0)) > 15:
        return headline[: m.start()]
    return headline


def load_handoff_records(date: str | None, cluster_id: int | None) -> list[dict]:
    if cluster_id is not None:
        paths = sorted(HANDOFF_DIR.glob(f"*/{cluster_id}.json"))
        if not paths:
            print(f"ERROR: no handoff file found for cluster {cluster_id} under {HANDOFF_DIR}")
            sys.exit(1)
    elif date:
        day_dir = HANDOFF_DIR / date
        if not day_dir.exists():
            print(f"ERROR: {day_dir} does not exist")
            sys.exit(1)
        paths = sorted(day_dir.glob("*.json"))
    else:
        paths = sorted(HANDOFF_DIR.glob("*/*.json"))

    return [json.loads(p.read_text(encoding="utf-8")) for p in paths]


def record_to_post(record: dict) -> dict:
    headline = clean_headline(record["canonical_headline"])
    sources = record.get("sources") or []
    primary_url = sources[0]["url"] if sources else ""

    return {
        "text": headline,
        "url": primary_url,
        "post_url": primary_url,
        "image_url": primary_url,  # presence-only routing flag -- see module docstring
        "_source_note": (
            f"AIM News Desk cluster {record.get('cluster_id')} "
            f"({len(sources)} source(s), "
            f"viral={record.get('scores', {}).get('viral_score_preliminary')}, "
            f"confidence={record.get('scores', {}).get('confidence_score')}, "
            f"verification={record.get('verification_status')})"
        ),
    }


def convert(records: list[dict]) -> list[dict]:
    # Preserve News Desk's own ranking -- batch_from_scrape.py takes posts in
    # INPUT ORDER, it does not re-sort by any engagement/viral signal itself.
    ordered = sorted(
        records, key=lambda r: r.get("scores", {}).get("viral_score_preliminary", 0), reverse=True
    )
    return [record_to_post(r) for r in ordered]


def main():
    ap = argparse.ArgumentParser(description="AIM News Desk -> First Signal News pipeline adapter")
    ap.add_argument("--date", help="YYYY-MM-DD handoff folder to convert (default: all dates)")
    ap.add_argument("--cluster-id", type=int, help="Convert a single cluster's handoff file")
    ap.add_argument(
        "--out", required=True,
        help="Output path, matching batch_from_scrape.py's --input. Never point this at "
             "the pipeline's real memory/scrape-results.json without deciding that on "
             "purpose -- that file is live production state.",
    )
    args = ap.parse_args()

    records = load_handoff_records(args.date, args.cluster_id)
    if not records:
        print("No handoff records found.")
        sys.exit(1)

    posts = convert(records)

    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(json.dumps(posts, indent=2), encoding="utf-8")

    print(f"Wrote {len(posts)} post(s) to {out_path}")
    for p in posts:
        print(f"  - {p['text'][:70]}")


if __name__ == "__main__":
    main()
